### ISSUE TITLE
MILES data Not Found

### ISSUE THREAD

**Issue by TheTwoBoom** [Chia-vie/mockingpy#5]
Die Links für die MILES Dateien sind nicht mehr aktuell
Alle Links sagen:
404 Not Found

**Comment by Chia-vie** [comment]
Das ist eigenartig, bei mir funktionieren sie, in Safari und Chrome. Du meinst die Links in der README.md Datei, richtig?

**Comment by TheTwoBoom** [comment]
Ja, die Links in der ReadMe.md mit Chorme und Firefox funktionieren nicht

**Comment by TheTwoBoom** [comment]
Problem gelöst:
Die Website hat kein HTTPS Support!
Bitte dazuschreiben!
